###  Pandas Assignment  ###

1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series
	Values
	Index
	Data type
	Mean
	Maximum
	Minimum

In [1]:
import pandas as pd

In [3]:
marks = pd.Series([78, 85, 92, 67, 88])             ## Creating Pandas Series

In [5]:
marks  #displaying the complete series

0    78
1    85
2    92
3    67
4    88
dtype: int64

In [18]:
print(f"values = {marks.values}")#displaying only values

values = [78 85 92 67 88]

In [19]:
print(f"indexs = {marks.index}")   #displaying only indexes

indexs = RangeIndex(start=0, stop=5, step=1)

In [ ]:
marks.dtype    #displaying the datatype

dtype('int64')

In [20]:
print(f"mean of the values = {marks.mean()}")     #displaying the mean of the values

mean of the values = 82.0

In [21]:
print(f" maximum value = {marks.max()}")

 maximum value = 92

In [22]:
print(f" Minimum value = {marks.min()}")

 Minimum value = 67

2. Create a Series containing:
 
   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
	Display the marks of Meena.

In [24]:
students = pd.Series(
    [85, 78, 92, 74, 88],
    index=["Asha", "Ravi", "Meena", "Kiran", "Arun"]
)

In [25]:
students

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64

In [26]:
#to display the marks of Meena
print(f"Obtained Marks of Meena = {students["Meena"]}")

Obtained Marks of Meena = 92

3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types

In [43]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

In [44]:
df   #display dataframe

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [45]:
df.head(3)     #first 3 rows

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

In [46]:
df.tail(2)     #last 2 rows

    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [47]:
df.shape

(5, 4)

In [48]:
df.columns

Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

In [49]:
df.dtypes

Name            str
Age           int64
Department      str
Marks         int64
dtype: object

4.  Using the previous DataFrame, display:

	info()
	describe()
	Number of rows
	Number of columns

In [50]:
df.info()   #to display dataframe information

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [51]:
df.describe() #display summary

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

In [52]:
df.shape[0]     #Number of rows

5

In [53]:
df.shape[1]     #Number of columns

4

5. Using df, display:

	Name column
	Marks column
	Name and Marks together

In [56]:
df["Name"]

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: str

In [57]:
df["Marks"]

0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

In [58]:
print("\nName and Marks:")
print(df[["Name", "Marks"]])

Name and Marks:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

6. Display:

	First row using iloc
	Third row using iloc
	Rows 1 to 3
	Name and Marks columns using loc

In [59]:
# First row using iloc
print("First row:")
print(df.iloc[0])

First row:
Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

In [60]:
# Third row using iloc
print("\nThird row:")
print(df.iloc[2])

Third row:
Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

In [61]:
# Rows 1 to 3
print("\nRows 1 to 3:")
print(df.iloc[1:4])

Rows 1 to 3:
    Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

In [62]:
# Name and Marks columns using loc
print("\nName and Marks:")
print(df.loc[:, ["Name", "Marks"]])

Name and Marks:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

7. Find:

	Students scoring above 80.
	Students scoring between 75 and 90.
	Students belonging to CSE.
	CSE students scoring above 80.

In [63]:
# Students scoring above 80
print("Students scoring above 80:")
print(df[df["Marks"] > 80])

Students scoring above 80:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [64]:
# Students scoring between 75 and 90
print("\nStudents scoring between 75 and 90:")
print(df[(df["Marks"] >= 75) & (df["Marks"] <= 90)])

Students scoring between 75 and 90:
   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [65]:
# Students belonging to CSE
print("\nStudents belonging to CSE:")
print(df[df["Department"] == "CSE"])

Students belonging to CSE:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [67]:
# CSE students scoring above 80
print("\nCSE students scoring above 80:")
print(df[(df["Department"] == "CSE") & (df["Marks"] > 80)])

CSE students scoring above 80:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

8. Display students belonging to either CSE or ECE.

In [68]:
(df["Department"] == "CSE") | (df["Department"] == "ECE")

0     True
1     True
2     True
3    False
4     True
Name: Department, dtype: bool

9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [69]:
# Add Result column
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 75 else "Fail")
df

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

In [70]:
# Assign grades
df["Grade"] = df["Marks"].apply(
    lambda x: "A" if x >= 90 else
              "B" if x >= 80 else
              "C" if x >= 70 else
              "D"
)

df

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

11. Sort students:

	By marks in ascending order.
	By marks in descending order.
	By Department and then Marks.

In [71]:
# Sort by Marks in ascending order
print("Marks - Ascending:")
print(df.sort_values("Marks"))

# Sort by Marks in descending order
print("\nMarks - Descending:")
print(df.sort_values("Marks", ascending=False))

# Sort by Department and then Marks
print("\nDepartment and then Marks:")
print(df.sort_values(["Department", "Marks"]))

Marks - Ascending:
    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Marks - Descending:
    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Department and then Marks:
    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:

Missing values
Number of missing values in each column
Rows containing missing values

In [73]:
import numpy as np

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

In [74]:
students.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

In [76]:
#Number of missing values in each column
students.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [77]:
#Rows containing missing values
students[students.isnull().any(axis=1)]

    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

13. Replace:

	Missing Age with average Age
	Missing Marks with average Marks

14. Remove rows containing missing values.

15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

Find duplicates:
Display duplicate rows:
Remove duplicates:

16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean
Median
Maximum
Minimum
Standard deviation
Sum

17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department
Maximum marks by department
Number of students in each department

For each department, calculate:
Mean
Minimum
Maximum
Count

18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.

19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

Display the first five records.
Find the dimensions of the dataset.
Find the average final mark.
Find the highest-scoring student.
Find the lowest-scoring student.
Display students scoring above 80.
Find average marks by department.
Find students having attendance above 80%.
Sort students by FinalMarks.
Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
Add a performance category:
	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement
Find the department having the highest average FinalMarks.

20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

Average salary.
Maximum and minimum salary.
Employee receiving the highest salary.
Employees earning above ₹60,000.
Average salary for each department.
Average experience by department.
Number of employees in each department.
Sort employees by salary.
Find IT employees with more than 3 years of experience.
Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low