###  Pandas Assignment  ###

1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series
	Values
	Index
	Data type
	Mean
	Maximum
	Minimum

In [2]:
import pandas as pd

In [3]:
marks = pd.Series([78, 85, 92, 67, 88])             ## Creating Pandas Series

In [4]:
marks  #displaying the complete series

0    78
1    85
2    92
3    67
4    88
dtype: int64

In [5]:
print(f"values = {marks.values}")#displaying only values

values = [78 85 92 67 88]

In [6]:
print(f"indexs = {marks.index}")   #displaying only indexes

indexs = RangeIndex(start=0, stop=5, step=1)

In [7]:
marks.dtype    #displaying the datatype

dtype('int64')

In [8]:
print(f"mean of the values = {marks.mean()}")     #displaying the mean of the values

mean of the values = 82.0

In [9]:
print(f" maximum value = {marks.max()}")

 maximum value = 92

In [10]:
print(f" Minimum value = {marks.min()}")

 Minimum value = 67

2. Create a Series containing:

   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
	Display the marks of Meena.

In [11]:
students = pd.Series(
    [85, 78, 92, 74, 88],
    index=["Asha", "Ravi", "Meena", "Kiran", "Arun"]
)

In [12]:
students

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64

In [13]:
#to display the marks of Meena
print(f"Obtained Marks of Meena = {students["Meena"]}")

Obtained Marks of Meena = 92

3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types

In [14]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE"],
    "Marks": [85, 78, 92, 74, 88]
}

df = pd.DataFrame(data)

In [15]:
df   #display dataframe

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [16]:
df.head(3)     #first 3 rows

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

In [17]:
df.tail(2)     #last 2 rows

    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

In [18]:
df.shape

(5, 4)

In [19]:
df.columns

Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')

In [20]:
df.dtypes

Name          object
Age            int64
Department    object
Marks          int64
dtype: object

4.  Using the previous DataFrame, display:

	info()
	describe()
	Number of rows
	Number of columns

In [21]:
df.info()   #to display dataframe information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [22]:
df.describe() #display summary

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

In [23]:
df.shape[0]     #Number of rows

5

In [24]:
df.shape[1]     #Number of columns

4

5. Using df, display:

	Name column
	Marks column
	Name and Marks together

In [25]:
df["Name"]

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: object

In [26]:
df["Marks"]

0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

In [27]:
print("\nName and Marks:")
print(df[["Name", "Marks"]])

Name and Marks:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

6. Display:

	First row using iloc
	Third row using iloc
	Rows 1 to 3
	Name and Marks columns using loc

In [28]:
# First row using iloc
print("First row:")
print(df.iloc[0])

First row:
Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

In [29]:
# Third row using iloc
print("\nThird row:")
print(df.iloc[2])

Third row:
Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

In [30]:
# Rows 1 to 3
print("\nRows 1 to 3:")
print(df.iloc[1:4])

Rows 1 to 3:
    Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

In [31]:
# Name and Marks columns using loc
print("\nName and Marks:")
print(df.loc[:, ["Name", "Marks"]])

Name and Marks:
    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

7. Find:

	Students scoring above 80.
	Students scoring between 75 and 90.
	Students belonging to CSE.
	CSE students scoring above 80.

In [32]:
# Students scoring above 80
print("Students scoring above 80:")
print(df[df["Marks"] > 80])

Students scoring above 80:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [33]:
# Students scoring between 75 and 90
print("\nStudents scoring between 75 and 90:")
print(df[(df["Marks"] >= 75) & (df["Marks"] <= 90)])

Students scoring between 75 and 90:
   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

In [34]:
# Students belonging to CSE
print("\nStudents belonging to CSE:")
print(df[df["Department"] == "CSE"])

Students belonging to CSE:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [35]:
# CSE students scoring above 80
print("\nCSE students scoring above 80:")
print(df[(df["Department"] == "CSE") & (df["Marks"] > 80)])

CSE students scoring above 80:
    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

8. Display students belonging to either CSE or ECE.

In [36]:
(df["Department"] == "CSE") | (df["Department"] == "ECE")

0     True
1     True
2     True
3    False
4     True
Name: Department, dtype: bool

9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [37]:
# Add Result column
df["Result"] = df["Marks"].apply(lambda x: "Pass" if x >= 75 else "Fail")
df

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

In [38]:
# Assign grades
df["Grade"] = df["Marks"].apply(
    lambda x: "A" if x >= 90 else
              "B" if x >= 80 else
              "C" if x >= 70 else
              "D"
)

df

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

11. Sort students:

	By marks in ascending order.
	By marks in descending order.
	By Department and then Marks.

In [39]:
# Sort by Marks in ascending order
print("Marks - Ascending:")
print(df.sort_values("Marks"))

# Sort by Marks in descending order
print("\nMarks - Descending:")
print(df.sort_values("Marks", ascending=False))

# Sort by Department and then Marks
print("\nDepartment and then Marks:")
print(df.sort_values(["Department", "Marks"]))

Marks - Ascending:
    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Marks - Descending:
    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Department and then Marks:
    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:

Missing values
Number of missing values in each column
Rows containing missing values

In [40]:
import numpy as np

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

In [41]:
students.isnull()

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

In [42]:
#Number of missing values in each column
students.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [43]:
#Rows containing missing values
students[students.isnull().any(axis=1)]

    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

13. Replace:

	Missing Age with average Age
	Missing Marks with average Marks

In [45]:
# Replace missing Age with average Age
students["Age"] = students["Age"].fillna(students["Age"].mean())
students["Age"]

0    22.00
1    23.00
2    22.75
3    24.00
4    22.00
Name: Age, dtype: float64

In [47]:
# Replace missing Marks with average Marks
students["Marks"] = students["Marks"].fillna(students["Marks"].mean())
students['Marks']

0    85.00
1    84.75
2    92.00
3    74.00
4    88.00
Name: Marks, dtype: float64

14. Remove rows containing missing values.

In [48]:
# Remove rows containing missing values
students_clean = students.dropna()

print(students_clean)

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

Find duplicates:
Display duplicate rows:
Remove duplicates:

In [49]:
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

In [50]:
df2

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

In [52]:
df2.duplicated()  #finding duplicate values

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [53]:
#Display duplicate rows
print("\nDuplicate rows:")
print(df2[df2.duplicated()])

Duplicate rows:
   Name  Marks
3  Asha     85

In [55]:
#Remove duplicates
df2 = df2.drop_duplicates()
df2

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean
Median
Maximum
Minimum
Standard deviation
Sum

In [56]:
marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

In [57]:
marks

  Student  Marks
0       A     78
1       B     85
2       C     92
3       D     67
4       E     88

In [58]:
print("Mean:", marks["Marks"].mean())

Mean: 82.0

In [59]:
print("Median:", marks["Marks"].median())

Median: 85.0

In [60]:
print("Maximum:", marks["Marks"].max())

Maximum: 92

In [61]:
print("Minimum:", marks["Marks"].min())

Minimum: 67

In [62]:
print("Standard Deviation:", marks["Marks"].std())

Standard Deviation: 9.82344135219425

In [63]:
print("Sum:", marks["Marks"].sum())

Sum: 410

17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department
Maximum marks by department
Number of students in each department

For each department, calculate:
Mean
Minimum
Maximum
Count

In [65]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)
df

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

In [66]:
# Average marks by department
print("Average marks by department:")
print(df.groupby("Department")["Marks"].mean())

Average marks by department:
Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

In [67]:
# Maximum marks by department
print("\nMaximum marks by department:")
print(df.groupby("Department")["Marks"].max())

Maximum marks by department:
Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

In [68]:
# Number of students in each department
print("\nNumber of students in each department:")
print(df.groupby("Department")["Name"].count())

Number of students in each department:
Department
CSE    3
ECE    2
ME     1
Name: Name, dtype: int64

In [69]:
# Mean, Minimum, Maximum and Count for each department
print("\nComplete department-wise statistics:")
print(df.groupby("Department")["Marks"].agg(["mean", "min", "max", "count"]))

Complete department-wise statistics:
                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.

In [74]:
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})
print(students)
print(marks)

   StudentID   Name
0        101   Asha
1        102   Ravi
2        103  Meena
3        104  Kiran
   StudentID  Marks
0        101     85
1        102     78
2        103     92
3        104     74

In [76]:
# Combine DataFrames using StudentID
result = pd.merge(students, marks, on="StudentID")
result

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

Display the first five records.
Find the dimensions of the dataset.
Find the average final mark.
Find the highest-scoring student.
Find the lowest-scoring student.
Display students scoring above 80.
Find average marks by department.
Find students having attendance above 80%.
Sort students by FinalMarks.
Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
Add a performance category:
	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement
Find the department having the highest average FinalMarks.

In [78]:
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)
df

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

In [79]:
df.head()

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

In [80]:
df.shape

(8, 5)

In [81]:
df["FinalMarks"].mean()  #finding avg of final marks

np.float64(81.625)

In [82]:
df.loc[df["FinalMarks"].idxmax()]    # Finding highest-scoring student

Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

In [83]:
df.loc[df["FinalMarks"].idxmin()]    #finding the lowest scoring student

Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

In [85]:
df[df["FinalMarks"] > 80]     # students scoring above 80

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [86]:
df.groupby("Department")["FinalMarks"].mean()    #average marks by department

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

In [87]:
df[df["Attendance"] > 80]    #students having attendence above 80

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

In [88]:
df.sort_values("FinalMarks", ascending=False)     #sorting students based on marks

    Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
7  Priya        ECE          95        91          93
5  Divya        CSE          88        86          89
0   Asha        CSE          92        85          88
4   Arun        ECE          82        80          83
1   Ravi        ECE          75        72          74
6   John         ME          72        70          68
3  Kiran         ME          68        65          62

In [91]:
# Adding Result column
df["Result"] = df["FinalMarks"].apply(
    lambda x: "Pass" if x >= 70 else "Fail"
)
df["Result"]

0    Pass
1    Pass
2    Pass
3    Fail
4    Pass
5    Pass
6    Fail
7    Pass
Name: Result, dtype: object

In [93]:
# Add Performance Category
df["Performance"] = df["FinalMarks"].apply(
    lambda x: "Excellent" if x >= 90 else
              "Very Good" if x >= 80 else
              "Good" if x >= 70 else
              "Needs Improvement"
)
df["Performance"]

0            Very Good
1                 Good
2            Excellent
3    Needs Improvement
4            Very Good
5            Very Good
6    Needs Improvement
7            Excellent
Name: Performance, dtype: object

In [94]:
#Department having highest average FinalMarks
dept_avg = df.groupby("Department")["FinalMarks"].mean()

print("\n12. Department with highest average FinalMarks:")
print(dept_avg.idxmax())

print("Average FinalMarks:",
      dept_avg.max())

12. Department with highest average FinalMarks:
CSE
Average FinalMarks: 91.0

20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

Average salary.
Maximum and minimum salary.
Employee receiving the highest salary.
Employees earning above ₹60,000.
Average salary for each department.
Average experience by department.
Number of employees in each department.
Sort employees by salary.
Find IT employees with more than 3 years of experience.
Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low

In [96]:
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

employees

  Employee Department  Experience  Salary
0      E01         IT           5   60000
1      E02         HR           3   45000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
6      E07         IT           2   48000
7      E08    Finance           5   70000

In [97]:
# 1. Average salary
print("1. Average salary:")
print(employees["Salary"].mean())

1. Average salary:
62875.0

In [98]:
# 2. Maximum and minimum salary
print("\n2. Maximum salary:")
print(employees["Salary"].max())

print("\nMinimum salary:")
print(employees["Salary"].min())

2. Maximum salary:
85000

Minimum salary:
45000

In [99]:
# 3. Employee receiving the highest salary
print("\n3. Employee receiving highest salary:")
print(employees.loc[employees["Salary"].idxmax()])

3. Employee receiving highest salary:
Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

In [100]:
# 4. Employees earning above ₹60,000
print("\n4. Employees earning above ₹60,000:")
print(employees[employees["Salary"] > 60000])

4. Employees earning above ₹60,000:
  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

In [101]:
# 5. Average salary for each department
print("\n5. Average salary by department:")
print(employees.groupby("Department")["Salary"].mean())

5. Average salary by department:
Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

In [102]:
# 6. Average experience by department
print("\n6. Average experience by department:")
print(employees.groupby("Department")["Experience"].mean())

6. Average experience by department:
Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

In [103]:
# 7. Number of employees in each department
print("\n7. Number of employees in each department:")
print(employees.groupby("Department")["Employee"].count())

7. Number of employees in each department:
Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [104]:
# 8. Sort employees by salary
print("\n8. Employees sorted by salary:")
print(employees.sort_values("Salary", ascending=False))

8. Employees sorted by salary:
  Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000

In [105]:
# 9. IT employees with more than 3 years of experience
print("\n9. IT employees with more than 3 years of experience:")
print(employees[
    (employees["Department"] == "IT") &
    (employees["Experience"] > 3)
])

9. IT employees with more than 3 years of experience:
  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

In [106]:
# 10. Add SalaryLevel column
employees["SalaryLevel"] = employees["Salary"].apply(
    lambda x: "High" if x >= 75000 else
              "Medium" if x >= 50000 else
              "Low"
)

print("\n10. DataFrame with SalaryLevel:")
print(employees)

10. DataFrame with SalaryLevel:
  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium